name: "Trigger .NET build"
on:
  workflow_dispatch:
  repository_dispatch:
  release:
    types: 
      - 'published'
      - 'unpublished'
      - 'edited'
    branches:
      - 'main'
      - 'ampere_main'

env:
  GH_ENTERPRISE_TOKEN: ${{ secrets.PAT_GITHUB }}

jobs:
  trigger-dot-net-build:
    runs-on: aws-runner-host-linux
    steps: 
      - uses: actions/github-script@v6
        with:
         github-token: ${{ secrets.PAT_GITHUB }}
         script: |
           await github.rest.actions.createWorkflowDispatch({
             owner: context.repo.owner,
             repo: 'DuckDB.NET',
             workflow_id: 'ci.yml',
             ref: 'main',
           })
